name: KBase Catalog test

on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - ready_for_review
  push:
    # run workflow when merging to main or develop
    branches:
      - main
      - master
      - develop

env:
  NMS_ADMIN_TOKEN: "o0xBDxPBVpqmezRtuDf4gdFYUIlFReH3kV1BOx75taCqzMvsvNnIDHzLITFTvGhNBzOT/hG/eEVDiKx/bnFoq0HJWsKYeKahOsiMlFavIR5jTIdMLq2zbZDkxV/+e0HoRRArWj53NV9wx0pWTv3DYxqbzPR1uu5letxdWnY3DQXggspcnJuAVYGn6LtgNM7MV+h3jdHe/E61LkwMff8KwpoBF+64AKbsZv1ddcFo0gbo9Z9CjLeBq4le2TwziLeuUYV885mPsRCvhToRMzpeVlbiNkzf7w5oh5g3FFsPOOYFeu22a+RrmKoM0hv9/pTTYG0G8/ylzOMIKWJvVrOJYptRvyQKmpmdcN7/CPYIQkf6ZBp0rP6G30Q2xt49+ST40ko1L0jhL42FfwXSmuNjklRMZAjpMNRZM2fIazEhDw3ND9l4T6HZnIwr/SQvKCs4rYBjqmSLo/dMISiFDLjWpMor5ew9fpZSLwJcPglGT0Anh4OIZUY2JGlO4TuOkq3m5kvXjjKLBc3Domd10c+DLfkldwwt6uqShsDECqFwSMf/liPEtLfi+03djrWvP26QeiEKL93ujAMS4oXAYxdquOy2Ib9ihd3XWTJzYc4s1H7furYqAbQDAhU0Dx3nvcyEsu5djdRAFe0eKUdjdAqsMAxe84h/EHZHrlE+KOOZo8s="

jobs:
  catalog_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: '3.7'
            mongo-version: '3.6'
          - python-version: '3.7'
            mongo-version: '7.0.4'
    services:
      mongo:
        image: mongo:${{matrix.python-version}}
        ports:
            - 27017:27017
        options: --name mongo${{matrix.python-version}}

    steps:
      - name: Repo checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}

      - name: Install dependencies and set up test config
        shell: bash
        run: |

          # test mongo connection
          curl http://localhost:27017
          returncode=$?
          if [ $returncode != 0 ]; then exit $returncode; fi

          # set HOMEDIR
          export HOMEDIR=`pwd`

          # move to parent dir to install binaries etc
          cd ..

          # setup kb-sdk
          mkdir -p $(pwd)/bin
          docker run kbase/kb-sdk genscript > $(pwd)/bin/kb-sdk
          chmod 755 $(pwd)/bin/kb-sdk
          export PATH=$(pwd)/bin:$PATH

          # install catalog dependencies
          cd $HOMEDIR
          pip install -r requirements.txt

          # setup test config
          cp -n test/test.cfg.example test/test.cfg
          sed -i "s#^nms-admin-token.*#nms-admin-token=$NMS_ADMIN_TOKEN#" test/test.cfg

      - name: Run tests
        shell: bash
        run: make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
